### PR TITLE
Add humans.txt

### PR DESCRIPTION
**Pull request by isayakmondal**
Added `humans.txt` as per the instruction in issue #220 

<a href="https://gitpod.io/#https://github.com/Xcov19/mycovidconnect/pull/221"></a>

---
This change is [Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/221)

### CODE REVIEW

**Review by codecakes — APPROVED** [review]
Very Nice. Approved!

**Comment by codecakes** [comment]
@isayakmondal merge this

**Comment by isayakmondal** [comment]
> @isayakmondal merge this

Hey, I'm so sorry but I couldn't understand what and where to merge? If possible could you elaborate?

**Comment by codecakes** [comment]
@isayakmondal click this:
image

**Comment by isayakmondal** [comment]
@codecakes I only have these two options over here.
image

**Comment by codecakes** [comment]
> @codecakes I only have these two options over here. There is no option for me to merge it. image

You should now be able to merge as well.

**Comment by isayakmondal** [comment]
Alright, did it :) @codecakes

**Pull request merged**
