### PR TITLE
[WIP] Installable WebApp

### LINKED ISSUE #215: Convert reactjs website into an installable webapp with push notifications.
**Is your feature request related to a problem? Please describe.**
The web service does not have an html app. The html app is needed for following reasons:
- A quick home link that can be installed to provide  push notifications
- The web app can access user geo-location to run a service worker that detects users location
- Can provide offline experience
- IO access becomes easier to offer better user experience like native apps

The outcome is detecting user presence and offering notifications that tell them when:
- nearby healthcare resources are available
- bookings are available
- scheduled requests are available

**Describe the solution you'd like**
Translate legacy reactjs site to an offline first mobile first responsive web app.

This should be a fairly hands-on simple task to make an installable web app. A stub push notification is required which notifies the user when the app has been installed on the device clicking on which should open the app.

**Additional context**

Setup to get an idea of the project:

1. The project repository is: https://github.com/Xcov19/mycovidconnect/

2. Follow the setup as per the ReadMe description provided there to setup the build locally.

3. Drop a message at reachout@mycovidconnect.com to receive the .env files.

4. Build the project and you should be able to see the basic setup;

Nice to have Pre-requisite before you start developing. Do this codelab:
https://web.dev/codelab-make-installable/

Tasks:
1. Follow PWA best practices.
2. Ensure the following is present in the web app manifest:
	- short name
	- name
	- icons: 192px and 512px
	- start_url
	- display - standalone
	- prefer_related_applications is set to false
3. Ensure service worker is registered with fetch handler.
4. The app should install as home screen shortcut.
5. Consider following in mind when you architect the solution:
	Storage
	bandwidth usage - fallback page?
	Encourage users to download the web app: (Read: https://web.dev/customize-install/)
		- Listen for the beforeinstallprompt event.
		- Save the beforeinstallprompt event, so it can be used to trigger the install flow later.
		- Alert the user that your PWA is installable, and provide a button or 
		other element to start the in-app installation flow.
	Read for references and best practices:
		https://web.dev/add-manifest/
		https://web.dev/promote-install/
		https://web.dev/customize-install/
6. Things to keep in mind when designing the solution:
	How will you design the Offline fallback page? Reference: https://web.dev/offline-fallback-page/
	How will you ensure this web app gets installed via Edge, Firefox, Opera, Samsung Internet, UC Browser
	For storage, what storage options do you feel best suits the need for various applications.
        Explore the app, see what storage requirements it has.

### PR DESCRIPTION
**Pull request by premalrupnur**
<a href="https://gitpod.io/#https://github.com/Xcov19/mycovidconnect/pull/159"></a>

---
This change is [Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/159)

### CODE REVIEW

**Comment by premalrupnur** [comment]
There are no errors in manifest file even then browser's console displays one error at line one in manifest file

**Comment by premalrupnur** [comment]
Screenshot (534)

**Review by codecakes — CHANGES_REQUESTED** [review]
this manifest should have atleast:
name,short_name, description, icons, start_url, display: fullscreen, standalone, minimal-ui, or browser; theme_color, background_color

**Comment by codecakes** [comment]
See: https://web.dev/progressive-web-apps/#installable

**Review by shehzad-haroon — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/159)* status: all files reviewed, 1 unresolved discussion (waiting on @premalrupnur)

___
*[mycovidconnect.webmanifest, line 3 at r1](https://reviewable.io/reviews/xcov19/mycovidconnect/159#-MndmGls8NyAs_1Pmw3f:-MndmGls8NyAs_1Pmw3g:bvkknxi) ([raw file](https://github.com/xcov19/mycovidconnect/blob/00a5e5e81ee913f2b49cba29373302e5f846593a/mycovidconnect.webmanifest#L3)):*
> ```JSON
> {
>     "name": "mycovidconnecct",
>     "short_name": "myc",
> ```

{
  "short_name": "mycovidconnecct",
  "name": "myc",
  "description": "Web app for covid patients",
  "icons": [
    {
      "src": "cookie-icon.ico",
      "sizes": "64x64",
      "type": "image/x-icon"
    },
    {
      "src": "192x192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "512x512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],
  "start_url": "/",
  "display": "standalone",
  "theme_color": "#000000",
  "background_color": "#ffffff"
}

**Review by shehzad-haroon — COMMENTED** [review]
{
  "short_name": "mycovidconnecct",
  "name": "myc",
  "description": "Web app for covid patients",
  "icons": [
    {
      "src": "cookie-icon.ico",
      "sizes": "64x64",
      "type": "image/x-icon"
    },
    {
      "src": "192x192.png",
      "type": "image/png",
      "sizes": "192x192"
    },
    {
      "src": "512x512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ],
  "start_url": "/",
  "display": "standalone",
  "theme_color": "#000000",
  "background_color": "#ffffff"
}

> *[Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/159#-:-Mndp3IZ6bTwOBDWlCeY:bvkknxi)* status: all files reviewed, 1 unresolved discussion (waiting on @premalrupnur)

**Review by shehzad-haroon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/159)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @premalrupnur and @shehzad-haroon)

___
*[public/index.html, line 24 at r1](https://reviewable.io/reviews/xcov19/mycovidconnect/159#-Mne3f-99wi41-T_RroD:-Mne3f-99wi41-T_RroE:b-4bpfju) ([raw file](https://github.com/xcov19/mycovidconnect/blob/00a5e5e81ee913f2b49cba29373302e5f846593a/public/index.html#L24)):*
> ```HTML
> </body>
> 
> </html>
> ```

<html>
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link type="text/plain" rel="author" href="humans.txt" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />
    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
    <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-app.js"></script>
    <script
      defer
      src="https://www.gstatic.com/firebasejs/7.17.1/firebase-analytics.js"
    ></script>
    <script
      defer
      src="https://www.gstatic.com/firebasejs/7.17.1/firebase-firestore.js"
    ></script>
    <script
      src="https://kit.fontawesome.com/0d4aacb00e.js"
      crossorigin="anonymous"
    ></script>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="manifest" href="%PUBLIC_URL%/web.webmanifest" />
    <title>MyCovidConnect: Find Nearest Healthcare facility</title>
    <style>
      .add-button {
        position: absolute;
        top: 1px;
        left: 1px;
      }
      .add-to-btn {
        background-color: #f15c08;
        padding: 10px;
        border: 0px;
        color: wheat;
        border-radius: 20px;
        font-weight: normal;
        text-transform: capitalize;
        font-family: "Lato", sans-serif;
      }
    </style>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <div class="add-to">
      <div style="position: fixed; bottom: 10px; right: 10px; color: green">
        <button class="add-to-btn">Install Our App</button>
      </div>
    </div>
    <script>
      if ("serviceWorker" in navigator) {
        window.addEventListener("load", function () {
          navigator.serviceWorker.register("/serviceworker.js").then(
            function (registration) {
              console.log(
                "ServiceWorker registration successful with scope: ",
                registration.scope
              );
            },
            function (err) {
              console.log("ServiceWorker registration failed: ", err);
            }
          );
        });
      }
      let deferredPrompt;
      var div = document.querySelector(".add-to");
      var button = document.querySelector(".add-to-btn");
      div.style.display = "none";
      window.addEventListener("beforeinstallprompt", (e) => {
        e.preventDefault();
        deferredPrompt = e;
        div.style.display = "block";
        console.log(`'beforeinstallprompt' event was fired.`);
        button.addEventListener("click", async () => {
          div.style.display = "none";
          deferredPrompt.prompt();
          const { outcome } = await deferredPrompt.userChoice;
          console.log(`User response to the install prompt: ${outcome}`);
          deferredPrompt = null;
        });
      });
    </script>
  </body>
</html>

**Review by shehzad-haroon — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/159#-:-Mne3tf3BOrwiYX6IMmp:bnfp4nl)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @premalrupnur and @shehzad-haroon)

**Comment by codecakes** [comment]
> :lgtm:
> 
> > Reviewed 1 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/159#-:-Mne3tf3BOrwiYX6IMmp:bnfp4nl)_ status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @premalrupnur and @shehzad-haroon)

Would be better to clean this up and re raise a fresh PR against develop

**Comment by codecakes** [comment]
Deprecated. Not useful.

**Pull request closed without merging**
