### PR TITLE
bumped node-forge to 0.10.0 - autoclosed

### PR DESCRIPTION
**Pull request by hannanel100**
This change is [Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/45)

### CODE REVIEW

**Review by codecakes — CHANGES_REQUESTED** [review]
add ".vscode/" in .gitignore.
Everything under it should be ignored

**Comment by hannanel100** [comment]
> add ".vscode/" in .gitignore.
> Everything under it should be ignored

Is the change i made in the second commit not correct?

**Comment by codecakes** [comment]
> > add ".vscode/" in .gitignore.
> > Everything under it should be ignored
> 
> Is the change i made in the second commit not correct?

Hi @hannanel100 i think the vscode dir is not ignored; maybe you added it to ignore after commit.
try `git rm --cached <dir>` you want to remove and then commit it;

Also test out with npm i if this it mentions there is a security vulnerability with this pkg; you can try npm audit

**Comment by hannanel100** [comment]
hope everything is ok now. I checked with npm i and got no security warnings for node-forge

**Comment by codecakes** [comment]
@akshayparmar90 @vasynizami can u guys look at this

**Comment by codecakes** [comment]
@hannanel100 i think you can resolve the above conflict and this should be good for a merge

**Pull request closed without merging**
