### PR TITLE
Update App.css

### PR DESCRIPTION
**Pull request by shivarajloni**
added changes with 2 indentations and updates the file

---
This change is [Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/128)

### CODE REVIEW

**Review by codecakes — CHANGES_REQUESTED** [review]
Need to be fixed

```bash
src/App.css
   2:5  ✖  Expected indentation of 2 spaces   indentation
   3:5  ✖  Expected indentation of 2 spaces   indentation
   7:8  ✖  Expected indentation of 2 spaces   indentation
   8:8  ✖  Expected indentation of 2 spaces   indentation
   9:8  ✖  Expected indentation of 2 spaces   indentation
  10:8  ✖  Expected indentation of 2 spaces   indentation
  20:9  ✖  Expected indentation of 2 spaces   indentation
  21:9  ✖  Expected indentation of 2 spaces   indentation
  22:9  ✖  Expected indentation of 2 spaces   indentation
  23:2  ✖  Expected indentation of 2 spaces   indentation
  27:3  ✖  Expected indentation of 2 spaces   indentation
  28:3  ✖  Expected indentation of 2 spaces   indentation
  29:3  ✖  Expected indentation of 2 spaces   indentation
  39:3  ✖  Expected indentation of 2 spaces   indentation
  40:3  ✖  Expected indentation of 2 spaces   indentation
  41:3  ✖  Expected indentation of 2 spaces   indentation
  45:3  ✖  Expected indentation of 2 spaces   indentation
  46:3  ✖  Expected indentation of 2 spaces   indentation
  47:3  ✖  Expected indentation of 2 spaces   indentation
  48:3  ✖  Expected indentation of 2 spaces   indentation
  52:3  ✖  Expected indentation of 2 spaces   indentation
  53:3  ✖  Expected indentation of 2 spaces   indentation
  54:3  ✖  Expected indentation of 2 spaces   indentation
  58:3  ✖  Expected indentation of 2 spaces   indentation
  59:3  ✖  Expected indentation of 2 spaces   indentation
  60:3  ✖  Expected indentation of 2 spaces   indentation
  61:3  ✖  Expected indentation of 2 spaces   indentation
  62:3  ✖  Expected indentation of 2 spaces   indentation
  66:3  ✖  Expected indentation of 2 spaces   indentation
  67:3  ✖  Expected indentation of 2 spaces   indentation
  68:3  ✖  Expected indentation of 2 spaces   indentation
  69:3  ✖  Expected indentation of 2 spaces   indentation
  70:3  ✖  Expected indentation of 2 spaces   indentation
  71:3  ✖  Expected indentation of 2 spaces   indentation
  72:3  ✖  Expected indentation of 2 spaces   indentation
  73:3  ✖  Expected indentation of 2 spaces   indentation
  77:3  ✖  Expected indentation of 2 spaces   indentation
  78:3  ✖  Expected indentation of 2 spaces   indentation
  82:3  ✖  Expected indentation of 2 spaces   indentation
  86:3  ✖  Expected indentation of 2 spaces   indentation
  87:3  ✖  Expected indentation of 2 spaces   indentation
  88:3  ✖  Expected indentation of 2 spaces   indentation
  92:3  ✖  Expected indentation of 2 spaces   indentation
  93:3  ✖  Expected indentation of 2 spaces   indentation
  94:3  ✖  Expected indentation of 2 spaces   indentation
  98:3  ✖  Expected indentation of 2 spaces   indentation
  99:3  ✖  Expected indentation of 2 spaces   indentation
 100:3  ✖  Expected indentation of 2 spaces   indentation
 101:3  ✖  Expected indentation of 2 spaces   indentation
 102:3  ✖  Expected indentation of 2 spaces   indentation
 103:3  ✖  Expected indentation of 2 spaces   indentation
 104:3  ✖  Expected indentation of 2 spaces   indentation
 108:3  ✖  Expected indentation of 2 spaces   indentation
 109:3  ✖  Expected indentation of 2 spaces   indentation
 110:3  ✖  Expected indentation of 2 spaces   indentation
 111:3  ✖  Expected indentation of 2 spaces   indentation
 112:3  ✖  Expected indentation of 2 spaces   indentation
 116:3  ✖  Expected indentation of 2 spaces   indentation
 117:3  ✖  Expected indentation of 2 spaces   indentation
 121:3  ✖  Expected indentation of 2 spaces   indentation
 122:3  ✖  Expected indentation of 2 spaces   indentation
 126:3  ✖  Expected indentation of 2 spaces   indentation
 127:3  ✖  Expected indentation of 2 spaces   indentation
 128:3  ✖  Expected indentation of 2 spaces   indentation
 132:3  ✖  Expected indentation of 2 spaces   indentation
 133:3  ✖  Expected indentation of 2 spaces   indentation
 143:3  ✖  Expected indentation of 2 spaces   indentation
 144:3  ✖  Expected indentation of 2 spaces   indentation
 145:3  ✖  Expected indentation of 2 spaces   indentation
 149:3  ✖  Expected indentation of 2 spaces   indentation
 150:3  ✖  Expected indentation of 2 spaces   indentation
 151:3  ✖  Expected indentation of 2 spaces   indentation
 161:3  ✖  Expected indentation of 2 spaces   indentation
 162:3  ✖  Expected indentation of 2 spaces   indentation
 163:3  ✖  Expected indentation of 2 spaces   indentation
 164:3  ✖  Expected indentation of 2 spaces   indentation
 165:3  ✖  Expected indentation of 2 spaces   indentation
 166:3  ✖  Expected indentation of 2 spaces   indentation
 167:3  ✖  Expected indentation of 2 spaces   indentation
 168:3  ✖  Expected indentation of 2 spaces   indentation
 169:3  ✖  Expected indentation of 2 spaces   indentation
 170:3  ✖  Expected indentation of 2 spaces   indentation
 171:3  ✖  Expected indentation of 2 spaces   indentation
 172:3  ✖  Expected indentation of 2 spaces   indentation
 176:3  ✖  Expected indentation of 2 spaces   indentation
 177:3  ✖  Expected indentation of 2 spaces   indentation
 178:3  ✖  Expected indentation of 2 spaces   indentation
 179:3  ✖  Expected indentation of 2 spaces   indentation
 180:3  ✖  Expected indentation of 2 spaces   indentation
 181:3  ✖  Expected indentation of 2 spaces   indentation
 185:3  ✖  Expected indentation of 2 spaces   indentation
 186:3  ✖  Expected indentation of 2 spaces   indentation
 187:3  ✖  Expected indentation of 2 spaces   indentation
 188:3  ✖  Expected indentation of 2 spaces   indentation
 189:3  ✖  Expected indentation of 2 spaces   indentation
 190:3  ✖  Expected indentation of 2 spaces   indentation
 194:3  ✖  Expected indentation of 2 spaces   indentation
 195:3  ✖  Expected indentation of 2 spaces   indentation
 196:3  ✖  Expected indentation of 2 spaces   indentation
 197:3  ✖  Expected indentation of 2 spaces   indentation
 198:3  ✖  Expected indentation of 2 spaces   indentation
 199:3  ✖  Expected indentation of 2 spaces   indentation
 200:3  ✖  Expected indentation of 2 spaces   indentation
 201:3  ✖  Expected indentation of 2 spaces   indentation
 205:3  ✖  Expected indentation of 2 spaces   indentation
 206:3  ✖  Expected indentation of 2 spaces   indentation
 207:3  ✖  Expected indentation of 2 spaces   indentation
 208:3  ✖  Expected indentation of 2 spaces   indentation
 209:3  ✖  Expected indentation of 2 spaces   indentation
 210:3  ✖  Expected indentation of 2 spaces   indentation
 211:3  ✖  Expected indentation of 2 spaces   indentation
 212:3  ✖  Expected indentation of 2 spaces   indentation
 213:3  ✖  Expected indentation of 2 spaces   indentation
 214:3  ✖  Expected indentation of 2 spaces   indentation
 215:3  ✖  Expected indentation of 2 spaces   indentation
 219:3  ✖  Expected indentation of 2 spaces   indentation
 223:3  ✖  Expected indentation of 2 spaces   indentation
 224:3  ✖  Expected indentation of 2 spaces   indentation
 225:3  ✖  Expected indentation of 2 spaces   indentation
 226:3  ✖  Expected indentation of 2 spaces   indentation
 227:3  ✖  Expected indentation of 2 spaces   indentation
 228:3  ✖  Expected indentation of 2 spaces   indentation
 229:3  ✖  Expected indentation of 2 spaces   indentation
 233:3  ✖  Expected indentation of 2 spaces   indentation
 234:3  ✖  Expected indentation of 2 spaces   indentation
 235:3  ✖  Expected indentation of 2 spaces   indentation
 236:3  ✖  Expected indentation of 2 spaces   indentation
 237:3  ✖  Expected indentation of 2 spaces   indentation
 238:3  ✖  Expected indentation of 2 spaces   indentation
 239:3  ✖  Expected indentation of 2 spaces   indentation
 249:3  ✖  Expected indentation of 2 spaces   indentation
 250:3  ✖  Expected indentation of 2 spaces   indentation
 251:3  ✖  Expected indentation of 2 spaces   indentation
 252:3  ✖  Expected indentation of 2 spaces   indentation
 253:3  ✖  Expected indentation of 2 spaces   indentation
 254:3  ✖  Expected indentation of 2 spaces   indentation
 258:3  ✖  Expected indentation of 2 spaces   indentation
 259:3  ✖  Expected indentation of 2 spaces   indentation
 260:3  ✖  Expected indentation of 2 spaces   indentation
 261:3  ✖  Expected indentation of 2 spaces   indentation
 262:3  ✖  Expected indentation of 2 spaces   indentation
 263:3  ✖  Expected indentation of 2 spaces   indentation
 264:3  ✖  Expected indentation of 2 spaces   indentation
 268:3  ✖  Expected indentation of 2 spaces   indentation
 269:3  ✖  Expected indentation of 2 spaces   indentation
 270:3  ✖  Expected indentation of 2 spaces   indentation
 271:3  ✖  Expected indentation of 2 spaces   indentation
 272:3  ✖  Expected indentation of 2 spaces   indentation
 273:3  ✖  Expected indentation of 2 spaces   indentation
 274:3  ✖  Expected indentation of 2 spaces   indentation
 278:3  ✖  Expected indentation of 2 spaces   indentation
 279:3  ✖  Expected indentation of 2 spaces   indentation
 280:3  ✖  Expected indentation of 2 spaces   indentation
 281:3  ✖  Expected indentation of 2 spaces   indentation
 285:3  ✖  Expected indentation of 2 spaces   indentation
 286:3  ✖  Expected indentation of 2 spaces   indentation
 287:3  ✖  Expected indentation of 2 spaces   indentation
 288:3  ✖  Expected indentation of 2 spaces   indentation
 289:3  ✖  Expected indentation of 2 spaces   indentation
 290:3  ✖  Expected indentation of 2 spaces   indentation
 291:3  ✖  Expected indentation of 2 spaces   indentation
 295:3  ✖  Expected indentation of 2 spaces   indentation
 296:3  ✖  Expected indentation of 2 spaces   indentation
 297:3  ✖  Expected indentation of 2 spaces   indentation
 298:3  ✖  Expected indentation of 2 spaces   indentation
 299:3  ✖  Expected indentation of 2 spaces   indentation
 303:3  ✖  Expected indentation of 2 spaces   indentation
 304:3  ✖  Expected indentation of 2 spaces   indentation
 305:3  ✖  Expected indentation of 2 spaces   indentation
 306:3  ✖  Expected indentation of 2 spaces   indentation
 310:3  ✖  Expected indentation of 2 spaces   indentation
 311:3  ✖  Expected indentation of 2 spaces   indentation
 312:3  ✖  Expected indentation of 2 spaces   indentation
 313:3  ✖  Expected indentation of 2 spaces   indentation
 314:3  ✖  Expected indentation of 2 spaces   indentation
 315:3  ✖  Expected indentation of 2 spaces   indentation
 316:3  ✖  Expected indentation of 2 spaces   indentation
 320:3  ✖  Expected indentation of 2 spaces   indentation
 321:3  ✖  Expected indentation of 2 spaces   indentation
 322:3  ✖  Expected indentation of 2 spaces   indentation
 323:3  ✖  Expected indentation of 2 spaces   indentation
 324:3  ✖  Expected indentation of 2 spaces   indentation
 328:3  ✖  Expected indentation of 2 spaces   indentation
 329:3  ✖  Expected indentation of 2 spaces   indentation
 330:3  ✖  Expected indentation of 2 spaces   indentation
 334:3  ✖  Expected indentation of 2 spaces   indentation
 335:3  ✖  Expected indentation of 2 spaces   indentation
 336:3  ✖  Expected indentation of 2 spaces   indentation
 337:3  ✖  Expected indentation of 2 spaces   indentation
 338:3  ✖  Expected indentation of 2 spaces   indentation
 339:3  ✖  Expected indentation of 2 spaces   indentation
 340:3  ✖  Expected indentation of 2 spaces   indentation
 341:3  ✖  Expected indentation of 2 spaces   indentation
 342:3  ✖  Expected indentation of 2 spaces   indentation
 346:3  ✖  Expected indentation of 2 spaces   indentation
 347:3  ✖  Expected indentation of 2 spaces   indentation
 348:3  ✖  Expected indentation of 2 spaces   indentation
 349:3  ✖  Expected indentation of 2 spaces   indentation
 350:3  ✖  Expected indentation of 2 spaces   indentation
 351:3  ✖  Expected indentation of 2 spaces   indentation
 352:3  ✖  Expected indentation of 2 spaces   indentation
 356:3  ✖  Expected indentation of 2 spaces   indentation
 357:3  ✖  Expected indentation of 2 spaces   indentation
 358:3  ✖  Expected indentation of 2 spaces   indentation
 359:3  ✖  Expected indentation of 2 spaces   indentation
 360:3  ✖  Expected indentation of 2 spaces   indentation
 361:3  ✖  Expected indentation of 2 spaces   indentation
 366:3  ✖  Expected indentation of 2 spaces   indentation
 367:3  ✖  Expected indentation of 2 spaces   indentation
 368:3  ✖  Expected indentation of 2 spaces   indentation
 369:3  ✖  Expected indentation of 2 spaces   indentation
 370:3  ✖  Expected indentation of 2 spaces   indentation
 371:3  ✖  Expected indentation of 2 spaces   indentation
 372:3  ✖  Expected indentation of 2 spaces   indentation
 373:3  ✖  Expected indentation of 2 spaces   indentation
 377:3  ✖  Expected indentation of 2 spaces   indentation
 382:3  ✖  Expected indentation of 2 spaces   indentation
 383:3  ✖  Expected indentation of 2 spaces   indentation
 384:3  ✖  Expected indentation of 2 spaces   indentation
 388:3  ✖  Expected indentation of 2 spaces   indentation
 389:3  ✖  Expected indentation of 2 spaces   indentation
 390:3  ✖  Expected indentation of 2 spaces   indentation
 391:3  ✖  Expected indentation of 2 spaces   indentation
 395:3  ✖  Expected indentation of 2 spaces   indentation
 396:3  ✖  Expected indentation of 2 spaces   indentation
 397:3  ✖  Expected indentation of 2 spaces   indentation
 398:3  ✖  Expected indentation of 2 spaces   indentation
 399:3  ✖  Expected indentation of 2 spaces   indentation
 403:3  ✖  Expected indentation of 2 spaces   indentation
 404:3  ✖  Expected indentation of 2 spaces   indentation
 405:3  ✖  Expected indentation of 2 spaces   indentation
 406:3  ✖  Expected indentation of 2 spaces   indentation
 407:3  ✖  Expected indentation of 2 spaces   indentation
 408:3  ✖  Expected indentation of 2 spaces   indentation
 409:3  ✖  Expected indentation of 2 spaces   indentation
 410:3  ✖  Expected indentation of 2 spaces   indentation
 411:3  ✖  Expected indentation of 2 spaces   indentation
 415:3  ✖  Expected indentation of 2 spaces   indentation
 416:3  ✖  Expected indentation of 2 spaces   indentation
 417:3  ✖  Expected indentation of 2 spaces   indentation
 418:3  ✖  Expected indentation of 2 spaces   indentation
 419:3  ✖  Expected indentation of 2 spaces   indentation
 420:3  ✖  Expected indentation of 2 spaces   indentation
 421:3  ✖  Expected indentation of 2 spaces   indentation
 422:3  ✖  Expected indentation of 2 spaces   indentation
 423:3  ✖  Expected indentation of 2 spaces   indentation
 424:3  ✖  Expected indentation of 2 spaces   indentation
 425:3  ✖  Expected indentation of 2 spaces   indentation
 426:3  ✖  Expected indentation of 2 spaces   indentation
 427:3  ✖  Expected indentation of 2 spaces   indentation
 428:3  ✖  Expected indentation of 2 spaces   indentation
 432:3  ✖  Expected indentation of 2 spaces   indentation
 433:3  ✖  Expected indentation of 2 spaces   indentation
 434:3  ✖  Expected indentation of 2 spaces   indentation
 435:3  ✖  Expected indentation of 2 spaces   indentation
 436:3  ✖  Expected indentation of 2 spaces   indentation
 437:3  ✖  Expected indentation of 2 spaces   indentation
 438:3  ✖  Expected indentation of 2 spaces   indentation
 439:3  ✖  Expected indentation of 2 spaces   indentation
 443:3  ✖  Expected indentation of 2 spaces   indentation
 444:3  ✖  Expected indentation of 2 spaces   indentation
 448:3  ✖  Expected indentation of 2 spaces   indentation
 449:3  ✖  Expected indentation of 2 spaces   indentation
 450:3  ✖  Expected indentation of 2 spaces   indentation
 451:3  ✖  Expected indentation of 2 spaces   indentation
 452:3  ✖  Expected indentation of 2 spaces   indentation
 453:3  ✖  Expected indentation of 2 spaces   indentation
```

**Comment by shivarajloni** [comment]
okay, i am working on the correction..

**Review by codecakes — APPROVED** [review]
Merge this branch

**Comment by shivarajloni** [comment]
can you add the hacktoberfest tags!

thanks

**Pull request merged**
