### PR TITLE
Update App.css

### PR DESCRIPTION
**Pull request by harindra2002**
Resolved the issue by incorporating all the changes @codecakes

---
This change is [Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/88)

### CODE REVIEW

**Comment by harindra2002** [comment]
kindly review it @codecakes

**Review by andyderek — APPROVED** [review]
Looks good.  Passes StyleLint.

**Review by codecakes — CHANGES_REQUESTED** [review]
@harindra2002 pls merge latest changes from main repo master branch

**Comment by harindra2002** [comment]
> @harindra2002 pls merge latest changes from main repo master branch

Latest changes  from the main repo master branch  merged into harindra2002:harindra2002-patch-1

**Comment by harindra2002** [comment]
merged  the recent merges(main repo master branch) also  @codecakes

**Review by codecakes — APPROVED** [review]
looks good! pls merge this. send another pr @harindra2002 adding your name to contributors here without the fancy header format: https://github.com/Xcov19/mycovidconnect#7-credits

**Comment by harindra2002** [comment]
> looks good! pls merge this. send another pr @harindra2002 adding your name to contributors here without the fancy header format: https://github.com/Xcov19/mycovidconnect#7-credits

Profile Added #105 @codecakes

**Pull request merged**
