### PR TITLE
[WIP]Empty State Register option

### PR DESCRIPTION
**Pull request by premalrupnur**
Screenshot (329)

This is how it looks 

<a href="https://gitpod.io/#https://github.com/Xcov19/mycovidconnect/pull/145"></a>

---
This change is [Reviewable](https://reviewable.io/reviews/xcov19/mycovidconnect/145)

### CODE REVIEW

**Comment by premalrupnur** [comment]
@codecakes  I have added href linking to auth0 flow , is it a expected way to link auth0 flow ???

**Comment by codecakes** [comment]
this isnt how it is done

**Comment by premalrupnur** [comment]
What should be done then ???

**Comment by codecakes** [comment]
you need to refer to react auth0 docs. Im working to expose the auth flow from backend itself so you don't need to recreate the flow from frontend now. it can be called from backend

**Comment by premalrupnur** [comment]
> you need to refer to react auth0 docs. Im working to expose the auth flow from backend itself so you don't need to recreate the flow from frontend now. it can be called from backend

Yeah I got it that was doubt I had

**Comment by premalrupnur** [comment]
I have created a fresh pr

**Pull request closed without merging**
